# Generated by Django 2.0.3 on 2018-03-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
