# Generated by Django 2.0.3 on 2018-03-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180324_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(default='default_user', max_length=15),
        ),
    ]
