# Generated by Django 2.0.3 on 2018-03-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180324_2221'),
    ]

    operations = [
    ]
