# Generated by Django 2.0.3 on 2018-03-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180325_0054'),
    ]

    operations = [
    ]
