# Generated by Django 2.0.3 on 2018-03-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180325_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postid',
        ),
    ]
