# Generated by Django 2.0.4 on 2018-04-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180408_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_created']},
        ),
    ]
