# Generated by Django 2.0.4 on 2018-05-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
