# Generated by Django 2.0.4 on 2018-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments_downvoted',
            field=models.ManyToManyField(blank=True, default=None, related_name='users_downvoted', to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comments_upvoted',
            field=models.ManyToManyField(blank=True, default=None, related_name='users_upvoted', to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts_downvoted',
            field=models.ManyToManyField(blank=True, default=None, related_name='users_downvoted', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts_upvoted',
            field=models.ManyToManyField(blank=True, default=None, related_name='users_upvoted', to='api.Post'),
        ),
    ]
