# Generated by Django 2.0.4 on 2018-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180502_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anon_author',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='next_new_commenter',
            field=models.IntegerField(default=1),
        ),
    ]
