# Generated by Django 2.0.4 on 2018-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.IntegerField()),
                ('user', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=5000)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
