# Generated by Django 2.0.4 on 2018-04-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postID',
        ),
    ]
